apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synara.fullname" . }}-secrets
type: Opaque
stringData:
  CAP_TOKEN_SECRET: {{ .Values.env.CAP_TOKEN_SECRET | quote }}
  WHISPER_SECRET: {{ .Values.env.WHISPER_SECRET | quote }}