apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resonance-mesh.fullname" . }}-secrets
  labels:
    {{- include "resonance-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  CAP_TOKEN_SECRET: {{ .Values.secretEnv.CAP_TOKEN_SECRET | quote }}
  WHISPER_SECRET: {{ .Values.secretEnv.WHISPER_SECRET | quote }}